CREATE TABLE TRANSLATES
(
    ID                 BIGSERIAL PRIMARY KEY NOT NULL,
    MESSAGE_ID         BIGINT                NOT NULL,
    TRANSLATE_RESULT   BYTEA,
    TRANSLATE_LANGUAGE VARCHAR(255)
);
