CREATE TABLE USERS
(
    ID         BIGSERIAL PRIMARY KEY NOT NULL,
    USER_ID    BIGINT                NOT NULL,
    USER_NAME  VARCHAR(256) NULL,
    FIRST_NAME VARCHAR(256) NULL,
    LAST_NAME  VARCHAR(256) NULL,
    CONSTRAINT UN_USER_ID UNIQUE (USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_USERS_USER_ID ON USERS(USER_ID);
