CREATE TABLE USERS
(
    ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    USER_NAME VARCHAR2(256) NULL,
    FIRST_NAME VARCHAR2(256) NULL,
    LAST_NAME VARCHAR2(256) NULL,
);

CREATE INDEX IF NOT EXISTS ON USERS(USER_ID);
