CREATE TABLE MESSAGES
(
    ID             LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USER_ID        NUMBER(19)                      NOT NULL,
    CHAT_ID        NUMBER(19)                      NOT NULL,
    MESSAGE_ID     NUMBER(19)                      NOT NULL,
    REQUEST_ID     VARCHAR(255)                    NOT NULL,
    TIMESTAMP      DATETIME                        NOT NULL,
    MESSAGE_VALUE  BLOB                            NULL,
    MESSAGE_RESULT BLOB                            NULL,
    STATUS         NUMBER(1)                       NULL,
    CONSTRAINT UN_REQUEST UNIQUE (REQUEST_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_STATUS FOREIGN KEY (STATUS) REFERENCES MESSAGE_STATUS (ID)
);

CREATE INDEX IF NOT EXISTS ON MESSAGES(MESSAGE_ID);
CREATE INDEX IF NOT EXISTS ON MESSAGES(CHAT_ID);
