ktor:
  application:
    modules:
      - storage.trans.com.ApplicationKt.module
  deployment:
    port: 8096


database:
  driverClass: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/testdb"
  user: "admin"
  password: "admin"
  maxPoolSize: 10

kafka:
  registryUrl: "http://127.0.0.1:8081"
  groupId: "test-group-id"
  producerClientId: "producerTestClientId"
  consumerClientId: "consumerTestClientId"
  topicName: "test-event-topic"
  bootstrapServers:
    - "http://127.0.0.1:29092"
