INSERT INTO TEST (DESCRIPTION, NAME)
VALUES ('Test1', 'NameTest1');

INSERT INTO TEST (DESCRIPTION, NAME)
VALUES ('Test2', 'NameTest2');

INSERT INTO TEST (DESCRIPTION, NAME)
VALUES ('Test3', 'NameTest3');
