ktor:
    application:
        modules:
            - com.trans.telegram.ApplicationKt.module
    deployment:
        port: 8097

kafka:
    groupId: "telegram-service-group"
    bootstrapServers:
        - "http://localhost:9092"
    producerTopics:
        - name: "tg-incoming-storage"
          senderType: "PROCESSING_SENDER"
    consumerTopics:
        - name: "tg-out-storage"
          handler: "PROCESSING_HANDLER"
          deserializerType: "com.trans.telegram.domain.ProcessingMessageResponse"

redis:
  address: "redis://localhost:6379"
  cacheMessageDuration: 600

