ktor:
    application:
        modules:
            - com.trans.ApplicationKt.module
    deployment:
        port: 8097

kafka:
    bootstrapServers:
        - "http://localhost:9092"
    producerTopics:
        - name: "tg-incoming-storage"
          senderType: "PROCESSING_SENDER"
    consumerTopics:
        - name: "tg-out-storage"
          handler: "PROCESSING_HANDLER"
          deserializerType: "com.trans.domain.ProcessingMessageResponse"

