ktor:
    application:
        modules:
            - com.trans.ApplicationKt.module
    deployment:
        port: 8095


database:
    driverClass: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"
    user: "root"
    password: "password"
    maxPoolSize: 10

kafka:
    registryUrl: "http://localhost:8081"
    groupId: "test-group-id"
    producerClientId: "producerTestClientId"
    consumerClientId: "consumerTestClientId"
    topicName: "test-event-topic"
    bootstrapServers:
        - "http://localhost:29092"
